### PR TITLE
Fixed the bugs of main.java file

### PR DESCRIPTION
**Pull request by GrgArjun**
@bomkhati Please send the file Main.java for review to @RoshanShr.

### CODE REVIEW

**Comment by RoshanShr** [comment]
Please check the variable names properly and make it more meaningful @bomkhati  @GrgArjun

**Comment by GrgArjun** [comment]
The variable name has been changed and made more meaningful. Please send it for review @bomkhati

**Comment by bomkhati** [comment]
@RoshanShr please review the file

**Comment by RoshanShr** [comment]
Code seems to be fine. @bomkhati please merge it.

**Pull request merged**
