### PR TITLE
variable name, function naming, and minor changes

### PR DESCRIPTION
**Pull request by bomkhati**

### CODE REVIEW

**Comment by RoshanShr** [comment]
@GrgArjun please verify the changes on loan.java file and please inform me if something is wrong

**Review by RoshanShr — COMMENTED** [review]
@GrgArjun please verify the changes on loan.java file and please inform me if something is wrong

**Comment by bomkhati** [comment]
@RoshanShr Changed variable names and function names in FixBookControl File

**Comment by GrgArjun** [comment]
@RoshanShr I had reviewed the file. Please merge it to master

**Pull request merged**
