### PR TITLE
Calendar.java file changed variables method and enum method on 

### PR DESCRIPTION
**Pull request by GrgArjun**
@bomkhati please check the file and assign for review

### CODE REVIEW

**Comment by bomkhati** [comment]
@RoshanShr please review the calendar file

**Comment by RoshanShr** [comment]
@bomkhati  there are some indentation issues in the code. Please fix it and rest is ok.

**Comment by bomkhati** [comment]
@GrgArjun  please check the indentation on files

**Comment by GrgArjun** [comment]
Indentation issues fixed. @bomkhati please send the file Calendar.java for review.

**Pull request merged**
